[package]
name = "qsp"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/QwexGP/qsp-protocol"
description = "Qwex Secure Protocol implementation"

[dependencies]
snow = "0.9.2"
rand = { version = "0.8.5", features = ["getrandom"] }
